# Generated by Django 2.1.7 on 2019-04-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('idApuesta', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fechaApuesta', models.DateField(auto_now=True)),
                ('montoApuesta', models.PositiveIntegerField(default=0)),
                ('gano', models.BooleanField(default=False)),
                ('valorganado', models.PositiveIntegerField(default=0)),
                ('nombreEquipo', models.CharField(max_length=100)),
                ('jornadaEncuentro', models.PositiveIntegerField(default=0)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
