# Generated by Django 2.1.7 on 2019-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apuesta',
            old_name='jornadaEncuentro',
            new_name='diferenciaGoles',
        ),
        migrations.AddField(
            model_name='apuesta',
            name='golesLocal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='golesVistante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='idPartido',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
