# Generated by Django 2.1.7 on 2019-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0002_auto_20190407_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apuesta',
            old_name='golesVistante',
            new_name='golesVisitante',
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='fechaApuesta',
            field=models.DateField(),
        ),
    ]
